drop table if exists configs;
DELIMITER ;
drop table if exists users_roles;
DELIMITER ;
drop table if exists social_network_mappings;
DELIMITER ;
drop table if exists addresses;
DELIMITER ;
drop table if exists contacts;
DELIMITER ;
drop table if exists sessions;
DELIMITER ;
drop table if exists user_keys;
DELIMITER ;
drop table if exists users;
DELIMITER ;
drop table if exists localized_strings;
DELIMITER ;
drop table if exists localized_string_names;
DELIMITER ;
delete from cultures;
DELIMITER ;
drop table if exists cultures;
DELIMITER ;
delete from roles;
DELIMITER ;
drop table if exists roles;
DELIMITER ;
delete from time_zones;
DELIMITER ;
drop table if exists time_zones;
