#!/bin/bash


./db/dbutil destroy --database nettools
./db/dbutil setup --database nettools
./db/dbutil migrate --database nettools

./db/dbutil destroy --database nettools_test
./db/dbutil setup --database nettools_test
./db/dbutil migrate --database nettools_test

