#!/bin/bash


./db/dbutil destroy --database digital_id
./db/dbutil setup --database digital_id
./db/dbutil migrate --database digital_id

./db/dbutil destroy --database digital_id_test
./db/dbutil setup --database digital_id_test
./db/dbutil migrate --database digital_id_test

